### ISSUE TITLE
Check if bower, npm, gulp are installed

### ISSUE THREAD

**Issue by hello-jason** [hello-jason/bedrock-sage-deploy-to-wpengine#2]
The script currently does not confirm if the user has these dependencies before running, and it will fail if they don't. Add these to the checks before it runs.

**Comment by cmckni3** [comment]
``` bash
type npm > /dev/null 2>&1 || { echo >&2 "npm is not installed"; exit 1 }
type bower > /dev/null 2>&1 || { echo >&2 "bower is not installed"; exit 1 }
type gulp > /dev/null 2>&1 || { echo >&2 "gulp is not installed"; exit 1 }
```

**Comment by hello-jason** [comment]
<3

**Comment by hello-jason** [comment]
- Need to add documentation
- Assumes composer is global

**Comment by hello-jason** [comment]
Considering removing theme-specific support, as per #13

**Comment by cmckni3** [comment]
Maybe have building as an opt-in feature and check for a `build.sh` file to run?

_EDIT_ Really it could be anything that is runnable via `chmod +x` and has a shebang line.

**Comment by hello-jason** [comment]
Done with 9f53804e4a72f936a73e288f49710c25c7425aab
